# Generated by Django 4.0.1 on 2022-01-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_id',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Received'), (2, 'Baking'), (3, 'Baked'), (4, 'Ready'), (5, 'Complete')], default=1),
        ),
    ]
